// react/src/components/header/header.tsx
import { useState } from 'react'

import './header.scss'

export function Header() {
  const [menuOpen, setMenuOpen] = useState(false)

  function toggleMenu() {
    setMenuOpen(!menuOpen)
  }

  function closeMenu() {
    setMenuOpen(false)
  }

  return (
    <header className="header w-full bg-white shadow-md">
      <div className="header__container max-w-6xl mx-auto px-4 py-3 flex items-center justify-between">

        {/* Logo */}
        <div className="flex items-center gap-1 cursor-pointer">
          <svg className="header__icon w-10 h-10">
            <use href="/svg/icons.svg#icon-cat" />
          </svg>

          <span className="hidden md:inline text-2xl font-semibold tracking-wider primary-color">
            CATLAB
          </span>
        </div>

        {/* Botão Mobile */}
        <button
          className="header__toggle md:hidden"
          onClick={toggleMenu}
        >
          <span className="primary-color">
            {menuOpen ? '✕' : '☰'}
          </span>
        </button>

        {/* Navegação */}
        <nav
          className={`header__nav ${menuOpen ? 'header__nav--open' : ''}`}
        >
          <a
            href="/"
            onClick={closeMenu}
            className="header__link"
          >
            HOME
          </a>

          <a
            href="/sobre"
            onClick={closeMenu}
            className="header__link"
          >
            SOBRE
          </a>

          <a
            href="/tecnologias"
            onClick={closeMenu}
            className="header__link"
          >
            TECNOLOGIAS
          </a>

          <a
            href="/doc/Analise_v1.0.pdf"
            target="_blank"
            rel="noopener noreferrer nofollow"
            className="header__link"
          >
            DOCS
          </a>
        </nav>
      </div>
    </header>
  )
}

// angular/src/app/shared/components/header/header.component.ts
import { Component } from '@angular/core';
import { MatIconModule } from '@angular/material/icon';

@Component({
  selector: 'app-header',
  imports: [
    MatIconModule
  ],
  standalone: true,
  templateUrl: './header.component.html',
  styleUrl: './header.component.scss',
})
export class HeaderComponent {

  public menuOpen: boolean = false;

  toggleMenu() {
    this.menuOpen = !this.menuOpen;
  }

  closeMenu() {
    this.menuOpen = false;
  }
}

<header class="header w-full bg-white shadow-md">
  <div class="header__container max-w-6xl mx-auto px-4 py-3 flex items-center justify-between">

    <!-- Logo -->
    <div class="flex items-center gap-1 cursor-pointer">
    	<svg class="header__icon w-10 h-10">
      	<use href="/svg/icons.svg#icon-cat"></use>
      </svg>

      <!-- some no mobile -->
      <span class="hidden md:inline text-2xl font-semibold tracking-wider primary-color">
        CATLAB
      </span>
    </div>

    <!-- Botão Mobile -->
    <button 
      class="header__toggle md:hidden"
      (click)="toggleMenu()"
    >
      <mat-icon class="primary-color">
        {{ menuOpen ? 'close' : 'menu' }}
      </mat-icon>
    </button>

    <!-- Navegação -->
    <nav 
      class="header__nav"
      [class.header__nav--open]="menuOpen"
    >
      <a routerLink="/" (click)="closeMenu()" class="header__link">HOME</a>
      <a routerLink="/sobre" (click)="closeMenu()" class="header__link">SOBRE</a>
      <a routerLink="/tecnologias" (click)="closeMenu()" class="header__link">TECNOLOGIAS</a>
      <a href="/doc/Analise_v1.0.pdf" target="_blank" rel="noopener noreferrer nofollow" class="header__link">
        DOCS
      </a>
    </nav>

  </div>
</header>
